# Generated by Django 4.1 on 2024-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
