# Generated by Django 4.1 on 2024-11-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAceptado',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido Aceptado',
                'verbose_name_plural': 'Pedidos Aceptados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tienda.pedido',),
        ),
        migrations.CreateModel(
            name='PedidoRechazado',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido Rechazado',
                'verbose_name_plural': 'Pedidos Rechazados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tienda.pedido',),
        ),
    ]
